# Generated by Django 5.0.6 on 2024-07-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_comment_post_like_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="dp",
            field=models.URLField(default=None),
        ),
    ]
