# Generated by Django 5.0.6 on 2024-07-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_alter_profile_dp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="person",
        ),
        migrations.AddField(
            model_name="post",
            name="Profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_of_poster",
                to="network.profile",
            ),
        ),
    ]
