# Generated by Django 5.0.6 on 2024-07-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0005_post_likes_delete_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="Profile",
            new_name="profile",
        ),
    ]
