# Generated by Django 5.0.6 on 2024-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0007_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
