# Generated by Django 4.1.7 on 2024-05-18 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_image_alter_listing_listing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 17, 10, 18, 21101)),
        ),
    ]
